const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { MemoryStore } = require('./core/memory-store')
const { CapabilityBroker } = require('./core/capability-broker')
const { ProviderRegistry } = require('./core/provider-registry')
const { createIdentity, encrypt, decrypt, roomKey, sign, verify } = require('./coop/crypto')
const { RoomService, PROTOCOL_VERSION } = require('./coop/room-service')
const { ArtifactStore } = require('./coop/artifact-store')

test('local SQLite memory separates roles, requires approval for lessons, and supports forgetting', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'youtube-office-memory-'))
  const store = new MemoryStore(dir)
  const lesson = store.add({ role: 'editor', kind: 'lesson', content: 'Keep the complete clutch payoff.', provenance: 'project-1', confidence: 0.9 })
  assert.equal(lesson.status, 'proposed')
  assert.equal(store.list({ role: 'researcher' }).length, 0)
  assert.equal(store.setStatus(lesson.id, 'approved').status, 'approved')
  assert.equal(store.list({ query: 'clutch' })[0].id, lesson.id)
  assert.equal(store.forget(lesson.id).status, 'forgotten')
})

test('capability grants are local, scoped, and never transferable by a remote participant', () => {
  const broker = new CapabilityBroker()
  const request = broker.request({ worker: 'editor', scope: 'render', resource: 'project-a', duration: 'project', projectId: 'project-a', reason: 'Render candidate' })
  assert.equal(broker.allows('editor', 'render', 'project-a', 'project-a'), false)
  broker.decide(request, true, 'local-user')
  assert.equal(broker.allows('editor', 'render', 'project-a', 'project-a'), true)
  assert.equal(broker.allows('researcher', 'render', 'project-a', 'project-a'), false)
})

test('provider registry supports per-worker Codex and Claude assignments', () => {
  const providers = new ProviderRegistry()
  providers.assign('researcher', 'claude')
  assert.equal(providers.forWorker('researcher').id, 'claude')
  assert.equal(providers.forWorker('editor').id, 'codex')
})

test('room cryptography encrypts payloads and signs exact envelopes', () => {
  const identity = createIdentity('Tester')
  const key = roomKey('amber-atlas-beacon-birch-canyon-cedar', Buffer.alloc(16, 7))
  const encrypted = encrypt(key, { message: 'private' }, 'room|sender|nonce|message')
  assert.equal(JSON.stringify(encrypted).includes('private'), false)
  assert.deepEqual(decrypt(key, encrypted, 'room|sender|nonce|message'), { message: 'private' })
  const body = JSON.stringify({ encrypted })
  assert.equal(verify(identity.publicKey, body, sign(identity, body)), true)
})

test('co-op envelopes reject replays and expose no private signing key', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'youtube-office-room-'))
  const rooms = new RoomService(dir, { label: 'Host' })
  const room = rooms.createRoom({ appVersion: '4.0.0', promptBundle: { shared: 'v1' } })
  const envelope = rooms.makeEnvelope(room.id, 'message', { text: 'hello' })
  assert.deepEqual(rooms.openEnvelope(room.id, envelope, rooms.identity.publicKey), { text: 'hello' })
  assert.throws(() => rooms.openEnvelope(room.id, envelope, rooms.identity.publicKey), /Replayed/)
  assert.equal(room.protocolVersion, PROTOCOL_VERSION)
  assert.equal('privateKey' in room, false)
  assert.equal('key' in room, false)
})

test('remote artifacts remain quarantined until explicit local approval', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'youtube-office-artifacts-'))
  const store = new ArtifactStore(dir)
  const received = store.receive({ ownerParticipantId: 'friend', taskId: 'project-1', name: '../../unsafe.exe', mimeType: 'application/octet-stream', bytes: Buffer.from('not executable test data') })
  assert.equal(received.quarantined, true)
  assert.equal(path.dirname(received.path), store.quarantine)
  assert.equal(received.name.includes('..'), false)
  const approved = store.approve(received)
  assert.equal(approved.quarantined, false)
  assert.equal(path.dirname(approved.path), store.approved)
  assert.equal(fs.existsSync(approved.path), true)
})
