const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('fs')
const path = require('path')

const bridgeSource = fs.readFileSync(path.join(__dirname, 'bridge-service.js'), 'utf8')

test('worker roles remain human and prompt-activated', () => {
  const source = bridgeSource
  assert.match(source, /Researcher \/ Planner/)
  assert.match(source, /Creative Director \/ Editor/)
  assert.match(source, /Manager \/ Publisher/)
  assert.match(source, /status: 'waiting'/)
  assert.doesNotMatch(source, /setInterval\([^)]*research/i)
})

test('GUI intake remains explicit and launches the autonomous handoff pipeline only after selection', () => {
  const source = bridgeSource
  assert.match(source, /\/task\/intake/)
  assert.match(source, /Do you already have a video or channel idea/)
  assert.match(source, /void runAutonomousPipeline\(state\.activeProject\)/)
  assert.match(source, /gpt-5\.6-luna/)
  assert.match(source, /gpt-5\.6-terra/)
  assert.match(source, /gpt-6-astra/)
  assert.match(source, /body\.intakeId !== state\.intake\.id/)
  assert.match(source, /body\.confirmed !== true/)
  assert.match(source, /A non-empty project title is required/)
})

test('real Codex workers run sequentially and expose lifecycle metadata', () => {
  const pipeline = bridgeSource.slice(bridgeSource.indexOf('async function runAutonomousPipeline'))
  const researcher = pipeline.indexOf("await runCodexWorker('researcher'")
  const editor = pipeline.indexOf("await runCodexWorker('editor'")
  const manager = pipeline.indexOf("await runCodexWorker('manager'")
  assert.ok(researcher > 0 && editor > researcher && manager > editor)
  assert.match(bridgeSource, /processId: child\.pid/)
  assert.match(bridgeSource, /startedAt/)
  assert.match(bridgeSource, /endedAt/)
  assert.match(bridgeSource, /exitCode/)
  assert.match(bridgeSource, /worker_started/)
  assert.match(bridgeSource, /worker_completed/)
})

test('timeline is sanitized and records reason, evidence, output, git and cost', () => {
  assert.match(bridgeSource, /\[REDACTED\]/)
  for (const field of ['reason:', 'evidence:', 'output:', 'git:', 'cost:']) assert.match(bridgeSource, new RegExp(field))
  assert.match(bridgeSource, /state\.timeline =/)
  assert.match(bridgeSource, /activity\.jsonl/)
})

test('usage falls back to authenticated local providers when the exact snapshot is stale', () => {
  assert.match(bridgeSource, /ordinaryUsageAllowed: null/)
  assert.match(bridgeSource, /policy: 'unknown'/)
  assert.match(bridgeSource, /resolveUsageAuthorization/)
  assert.match(bridgeSource, /local-authenticated-provider/)
  assert.match(bridgeSource, /Exact usage unavailable — your local signed-in provider will enforce its limits/)
  assert.match(bridgeSource, /ordinaryUsageAllowed !== true/)
  assert.match(bridgeSource, /provider-authentication-required/)
  assert.doesNotMatch(bridgeSource, /fiveHourUsedPercent:\s*29/)
  assert.doesNotMatch(bridgeSource, /weeklyUsedPercent:\s*96/)
  assert.doesNotMatch(bridgeSource, /weekly\s*>=\s*(75|90)/)
})

test('cancel, failure and restart recovery preserve completed checkpoints', () => {
  assert.match(bridgeSource, /\/task\/cancel/)
  assert.match(bridgeSource, /\/task\/restart/)
  assert.match(bridgeSource, /restart_recovery_required/)
  assert.match(bridgeSource, /completedStages/)
  assert.match(bridgeSource, /pipeline_blocked/)
  assert.match(bridgeSource, /pipeline_cancelled/)
})

test('completed runs emit postmortem and durable run memory while idle has no polling loop', () => {
  assert.match(bridgeSource, /postmortem\.md/)
  assert.match(bridgeSource, /run-memory\.json/)
  assert.match(bridgeSource, /Preserve completed checkpoints/)
  assert.doesNotMatch(bridgeSource, /setInterval\(/)
  assert.doesNotMatch(bridgeSource, /setTimeout\([^)]*runAutonomousPipeline/)
})

test('standalone room is compact, furnished, and includes a separate manager office', () => {
  const source = require('fs').readFileSync(require('path').join(__dirname, '..', 'standalone-server.js'), 'utf8')
  assert.match(source, /const cols = 16/)
  assert.match(source, /const rows = 12/)
  assert.match(source, /managerWall/)
  assert.match(source, /type: 'printer'/)
  assert.match(source, /type: 'paper_stack'/)
})

test('permanent versioned prompts include role boundaries, quirks, reflections, and shared rules', () => {
  const promptModule = fs.readFileSync(path.join(__dirname, 'prompts.js'), 'utf8')
  const promptDir = path.join(__dirname, 'prompts')
  const shared = fs.readFileSync(path.join(promptDir, 'shared-protocol.md'), 'utf8')
  const researcher = fs.readFileSync(path.join(promptDir, 'researcher.md'), 'utf8')
  const editor = fs.readFileSync(path.join(promptDir, 'editor.md'), 'utf8')
  const manager = fs.readFileSync(path.join(promptDir, 'manager.md'), 'utf8')
  assert.match(promptModule, /buildWorkerPrompt/)
  assert.match(promptModule, /sha256/)
  assert.match(shared, /challenge → evidence → alternative → decision/)
  assert.match(shared, /Reflection/)
  assert.match(researcher, /hot trail/)
  assert.match(researcher, /receipts/)
  assert.match(editor, /earn its place/)
  assert.match(editor, /coffee has gone cold/)
  assert.match(manager, /first dollar/)
  assert.match(manager, /approval stamp or desk bell/)
})

test('prompt compatibility hashes ignore BOM and platform newlines', () => {
  const { canonicalPromptText, promptVersion } = require('./prompts')
  assert.equal(canonicalPromptText('\uFEFFone\r\ntwo\r\n'), 'one\ntwo')
  assert.equal(promptVersion('one\r\ntwo\r\n'), promptVersion('one\ntwo\n'))
})

test('state v12 migrates chats, delivery, publishing, providers, permissions, workdays, side tasks, usage reports, co-op, prompts and desktop connection', () => {
  assert.match(bridgeSource, /version: 12/)
  assert.match(bridgeSource, /promptVersions/)
  assert.match(bridgeSource, /desktopConnection/)
  assert.match(bridgeSource, /roleChallenges/)
  assert.match(bridgeSource, /office_review/)
  assert.match(bridgeSource, /reviewReminders/)
  assert.match(bridgeSource, /projectLessons/)
  assert.match(bridgeSource, /providerAssignments/)
  assert.match(bridgeSource, /capabilityGrants/)
  assert.match(bridgeSource, /workday/)
  assert.match(bridgeSource, /coop/)
  assert.match(bridgeSource, /agentChats/)
  assert.match(bridgeSource, /chatQueues/)
  assert.match(bridgeSource, /teamConversations/)
  assert.match(bridgeSource, /legacyQueue\.filter/)
  assert.match(bridgeSource, /chatMetrics/)
  assert.match(bridgeSource, /machineId: `youtube-office-\$\{id\}`/)
  assert.match(bridgeSource, /stageDurationHistory/)
  assert.match(bridgeSource, /sideTasks/)
  assert.match(bridgeSource, /workdayUsageReports/)
  assert.match(bridgeSource, /productionTelemetry/)
  assert.match(bridgeSource, /deliveryManifests/)
  assert.match(bridgeSource, /publishJobs/)
  assert.match(bridgeSource, /revisionFamilies/)
  assert.match(bridgeSource, /youtubeConnection/)
  assert.match(bridgeSource, /\/role\/assign/)
  assert.match(bridgeSource, /role_redirect_resolved/)
})

test('co-op guest compatibility is validated before persistence and requires a transport URL', () => {
  const route = bridgeSource.slice(bridgeSource.indexOf("url.pathname === '/coop/join'"), bridgeSource.indexOf("url.pathname === '/coop/connect'"))
  assert.ok(route.indexOf('body.invite.appVersion') < route.indexOf('roomService.joinRoom'))
  assert.match(route, /A ws:\/\/ LAN or wss:\/\/ relay URL is required/)
  assert.match(route, /coopTransport\.connect\(body\.url/)
})

test('4.1 co-op keeps six visible workers, local usage ownership, paired handoffs, and shared project opt-in', () => {
  const app = fs.readFileSync(path.join(__dirname, '..', 'webview-ui', 'src', 'App.tsx'), 'utf8')
  const panel = fs.readFileSync(path.join(__dirname, '..', 'webview-ui', 'src', 'components', 'YouTubeOfficePanel.tsx'), 'utf8')
  const officeState = fs.readFileSync(path.join(__dirname, '..', 'webview-ui', 'src', 'office', 'engine', 'officeState.ts'), 'utf8')
  assert.match(app, /remote-researcher/)
  assert.match(app, /320211/)
  assert.match(officeState, /yt-review-chair-top/)
  assert.match(panel, /Approve for this project & join/)
  assert.match(panel, /Join shared project with my crew/)
  assert.match(bridgeSource, /resolveUsageAuthorization/)
  assert.match(bridgeSource, /usageAuthorization/)
  assert.match(bridgeSource, /project-started/)
  assert.match(bridgeSource, /project-joined/)
  assert.match(bridgeSource, /role-handoff/)
  assert.match(bridgeSource, /Both local Managers must approve/)
})

test('3.2 employee chat is independent, read-only, role-scoped, retryable, and cannot trigger production', () => {
  const root = path.join(__dirname, '..')
  const dock = fs.readFileSync(path.join(root, 'webview-ui', 'src', 'components', 'YouTubeOfficeChatDock.tsx'), 'utf8')
  const renderer = fs.readFileSync(path.join(root, 'webview-ui', 'src', 'office', 'engine', 'renderer.ts'), 'utf8')
  const codexAdapter = fs.readFileSync(path.join(__dirname, 'providers', 'codex-adapter.js'), 'utf8')
  assert.match(codexAdapter, /'read-only'/)
  assert.match(codexAdapter, /model_reasoning_effort/)
  assert.match(bridgeSource, /activeChatProcesses\[agentId\]/)
  assert.match(bridgeSource, /processAgentChatQueue\(id\)/)
  assert.match(bridgeSource, /state\.chatQueues\[agentId\]/)
  assert.match(bridgeSource, /CHAT_TIMEOUT_MS = 90 \* 1000/)
  assert.match(codexAdapter, /--ignore-user-config/)
  assert.match(codexAdapter, /--ignore-rules/)
  assert.match(bridgeSource, /provider\.chat/)
  assert.match(bridgeSource, /existing-credits-authorized/)
  assert.doesNotMatch(bridgeSource.match(/function processAgentChatQueue[\s\S]*?\n}/)?.[0] || '', /usageGate\(|pipelineRunning|desktopConnection/)
  assert.match(bridgeSource, /\/chat\\\/\(researcher\|editor\|manager\)\\\/messages/)
  assert.match(bridgeSource, /url\.pathname === '\/chat\/team\/messages'/)
  assert.match(bridgeSource, /conversationScope: 'team'/)
  assert.match(bridgeSource, /setImmediate\(processChatQueue\)/)
  assert.doesNotMatch(dock, /\/task\/start/)
  assert.match(dock, /Retry \{LABELS\[agentId\]\}/)
  assert.match(dock, /Send to 3/)
  assert.match(dock, /One message · three independent personality-driven replies/)
  assert.match(dock, /Conversation History|conversation history/)
  assert.doesNotMatch(dock, /yt-office-chat-transcript/)
  assert.match(dock, /youtube-office-agent-thinking/)
  assert.match(renderer, /wrapTextToLines\(ctx, ch\.speechText \|\| '', maxWidthPx, 4\)/)
  assert.match(renderer, /occupied\.find/)
})

test('manual End Workday reuses saved reflections and historical reminders remain locally gated', () => {
  assert.match(bridgeSource, /extractReflection\(researchFile/)
  assert.match(bridgeSource, /extractReflection\(editFile/)
  assert.match(bridgeSource, /extractReflection\(finalManagerFile/)
  assert.match(bridgeSource, /workday_reflection_saved/)
  assert.match(bridgeSource, /url\.pathname === '\/workday\/end'/)
  assert.match(bridgeSource, /End Workday meetings are disabled in co-op mode/)
  assert.match(bridgeSource, /No model work starts without explicit approval/)
  assert.match(bridgeSource, /historical_review_approved/)
})

test('YouTube Office 4.2.1 preserves readable controls, character-following speech, role movement, and local sounds', () => {
  const root = path.join(__dirname, '..')
  const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'))
  const preload = fs.readFileSync(path.join(root, 'electron', 'preload.cjs'), 'utf8')
  const panel = fs.readFileSync(path.join(root, 'webview-ui', 'src', 'components', 'YouTubeOfficePanel.tsx'), 'utf8')
  const officeState = fs.readFileSync(path.join(root, 'webview-ui', 'src', 'office', 'engine', 'officeState.ts'), 'utf8')
  const sounds = fs.readFileSync(path.join(root, 'webview-ui', 'src', 'notificationSound.ts'), 'utf8')
  const styles = fs.readFileSync(path.join(root, 'webview-ui', 'src', 'index.css'), 'utf8')
  const standalone = fs.readFileSync(path.join(root, 'standalone-server.js'), 'utf8')
  assert.equal(pkg.version, '4.2.1')
  assert.equal(pkg.displayName, 'YouTube Office 4.2.1')
  assert.match(preload, /minimize-window/)
  assert.match(preload, /data-office-window-control/)
  assert.match(panel, /youtube-office-agent-speech/)
  assert.match(officeState, /setCharacterSpeechByRole/)
  assert.match(officeState, /role === 'manager'/)
  assert.match(officeState, /walkSpeedMultiplier: 1\.35/)
  assert.match(sounds, /playMessageSound/)
  assert.match(sounds, /playUiSound/)
  assert.match(sounds, /playApprovalSound/)
  assert.match(styles, /width: 420px/)
  assert.match(styles, /font-size: 18px !important/)
  assert.match(standalone, /yt-first-dollar/)
  assert.match(standalone, /yt-water-cooler/)
})

test('4.2.1 delivers one verified final artifact and stages YouTube publishing privately', () => {
  const root = path.join(__dirname, '..')
  const delivery = fs.readFileSync(path.join(__dirname, 'core', 'delivery-manager.js'), 'utf8')
  const publisher = fs.readFileSync(path.join(__dirname, 'core', 'youtube-publisher.js'), 'utf8')
  const secrets = fs.readFileSync(path.join(__dirname, 'core', 'windows-secret-store.js'), 'utf8')
  const paths = fs.readFileSync(path.join(__dirname, 'paths.js'), 'utf8')
  const controls = fs.readFileSync(path.join(root, 'webview-ui', 'src', 'components', 'YouTubeOfficeControlCenter.tsx'), 'utf8')
  assert.match(delivery, /Finished-product hash verification failed/)
  assert.match(delivery, /previous-deliverables/)
  assert.match(delivery, /candidatePath/)
  assert.match(publisher, /privacyStatus: 'private'/)
  assert.match(publisher, /uploadType=resumable/)
  assert.match(publisher, /processingStatus/)
  assert.match(secrets, /ProtectedData.*Protect/)
  assert.match(secrets, /DataProtectionScope.*CurrentUser/)
  assert.match(bridgeSource, /RELEASE_DECISION: APPROVED/)
  assert.match(bridgeSource, /youtube_publish_verified/)
  assert.match(bridgeSource, /priorVideoRestored/)
  assert.match(paths, /YOUTUBE_OFFICE_FINISHED_ROOT/)
  assert.match(controls, /Automatic publishing/)
  assert.match(controls, /Open finished product/)
  assert.match(controls, /Copy path/)
})

test('YouTube Office owns a permanent clickable roster and suppresses the generic reporter waiting screen', () => {
  const root = path.join(__dirname, '..')
  const app = fs.readFileSync(path.join(root, 'webview-ui', 'src', 'App.tsx'), 'utf8')
  const messages = fs.readFileSync(path.join(root, 'webview-ui', 'src', 'hooks', 'useExtensionMessages.ts'), 'utf8')
  assert.match(messages, /YOUTUBE_OFFICE_ROSTER/)
  assert.match(messages, /Researcher/)
  assert.match(messages, /Editor/)
  assert.match(messages, /Manager/)
  assert.match(messages, /persistentYouTubeOffice/)
  assert.match(app, /!isYouTubeOffice && agents\.length === 0/)
  assert.match(app, /setYoutubeOfficeChatTarget\(role\)/)
  assert.match(app, /useState<OfficeChatTarget>\('team'\)/)
  assert.match(app, /<YouTubeOfficeChatDock target=\{youtubeOfficeChatTarget\}/)
})

test('portable installation uses per-user paths and never embeds the owner profile', () => {
  const root = path.join(__dirname, '..')
  const paths = fs.readFileSync(path.join(__dirname, 'paths.js'), 'utf8')
  const electron = fs.readFileSync(path.join(root, 'electron', 'main.cjs'), 'utf8')
  const installer = fs.readFileSync(path.join(root, 'scripts', 'install-youtube-office.ps1'), 'utf8')
  assert.match(paths, /YOUTUBE_OFFICE_CONTENT_ROOT/)
  assert.match(paths, /YOUTUBE_OFFICE_DATA_DIR/)
  assert.match(paths, /config\.json/)
  assert.match(paths, /replace\(\/\^\\uFEFF\//)
  assert.doesNotMatch(paths + electron + installer, /C:\\\\Users\\\\Owner/i)
  assert.match(installer, /MASTER_PROMPT\.md/)
  assert.match(installer, /-not \(Test-Path -LiteralPath \$MasterPrompt\)/)
})

test('a simulated hour of idle behavior contains no model or project trigger', () => {
  // The local render loop may tick for an hour; model work can only begin at
  // the explicit intake-confirmed HTTP path, never from a timer or idle phrase.
  const panel = fs.readFileSync(path.join(__dirname, '..', 'webview-ui', 'src', 'components', 'YouTubeOfficePanel.tsx'), 'utf8')
  assert.match(panel, /Start a project/)
  assert.match(bridgeSource, /body\.confirmed !== true/)
  assert.doesNotMatch(bridgeSource, /setInterval\(/)
  assert.doesNotMatch(panel, /setInterval\([^)]*(task\/start|runAutonomousPipeline|WebSearch)/)
  const simulatedSeconds = 60 * 60
  assert.equal(simulatedSeconds, 3600)
})

test('usage blocking pauses production without removing permanent workers or employee chat', () => {
  const extensionMessages = fs.readFileSync(path.join(__dirname, '..', 'webview-ui', 'src', 'hooks', 'useExtensionMessages.ts'), 'utf8')
  const panel = fs.readFileSync(path.join(__dirname, '..', 'webview-ui', 'src', 'components', 'YouTubeOfficePanel.tsx'), 'utf8')
  const chatQueue = bridgeSource.match(/function processAgentChatQueue[\s\S]*?\n}/)?.[0] || ''
  assert.match(extensionMessages, /YOUTUBE_OFFICE_ROSTER/)
  assert.match(panel, /Start a project — usage blocked/)
  assert.match(panel, /Open Providers/)
  assert.doesNotMatch(chatQueue, /usageGate\(|ordinaryUsageAllowed|desktopConnection/)
})

test('4.2 preserves one project-scoped approval bundle and excludes destructive and publish access', () => {
  const panel = fs.readFileSync(path.join(__dirname, '..', 'webview-ui', 'src', 'components', 'YouTubeOfficePanel.tsx'), 'utf8')
  assert.match(bridgeSource, /capabilityApprovalBundle/)
  assert.match(bridgeSource, /approveProjectCapabilityBundle/)
  assert.match(bridgeSource, /return json\(res, 428/)
  assert.match(bridgeSource, /approveProjectCapabilities/)
  assert.match(bridgeSource, /excludes: \['destructive', 'publish'\]/)
  assert.match(panel, /Approve for this project & start/)
  assert.match(panel, /Destructive and publishing access are not included/)
  assert.doesNotMatch(bridgeSource.match(/const PRODUCTION_CAPABILITIES = \{[\s\S]*?\n\}/)?.[0] || '', /publish|destructive/)
})

test('4.2 side assignments are explicit, economical, production-safe, and locally queued', () => {
  const dock = fs.readFileSync(path.join(__dirname, '..', 'webview-ui', 'src', 'components', 'YouTubeOfficeChatDock.tsx'), 'utf8')
  assert.match(dock, /Research &amp; answer/)
  assert.match(dock, /Mini project/)
  assert.match(dock, /Are you sure\?/)
  assert.match(bridgeSource, /SIDE_RESEARCH_TIMEOUT_MS/)
  assert.match(bridgeSource, /SIDE_MINI_TIMEOUT_MS/)
  assert.match(bridgeSource, /if \(activeSideProcess \|\| state\.sideTaskRuntime\?\.taskId\) return/)
  assert.match(bridgeSource, /sandbox: task\.mode === 'mini-project' \? 'workspace-write' : 'read-only'/)
  assert.match(bridgeSource, /reasoning = 'low'/)
  assert.match(bridgeSource, /excludes: \['destructive', 'publish'\]/)
  assert.match(bridgeSource, /sideTaskAgentAvailable/)
  assert.match(bridgeSource, /url\.pathname === '\/side-tasks'/)
  assert.match(bridgeSource, /side-task-result/)
})

test('4.2 local supervisor and workday reports avoid fabricated usage values', () => {
  const panel = fs.readFileSync(path.join(__dirname, '..', 'webview-ui', 'src', 'components', 'YouTubeOfficePanel.tsx'), 'utf8')
  const controls = fs.readFileSync(path.join(__dirname, '..', 'webview-ui', 'src', 'components', 'YouTubeOfficeControlCenter.tsx'), 'utf8')
  assert.match(bridgeSource, /startProductionSupervisor/)
  assert.match(bridgeSource, /modelUsageActive/)
  assert.match(bridgeSource, /createWorkdayUsageReport/)
  assert.match(bridgeSource, /Provider token counts unavailable; no values were estimated/)
  assert.match(bridgeSource, /Provider cost unavailable; no monetary estimate was invented/)
  assert.match(bridgeSource, /url\.pathname === '\/workday\/report'/)
  assert.match(panel, /local processing; no model usage currently/)
  assert.match(controls, /Usage Reports/)
  assert.match(controls, /Create my private session usage report/)
})
