const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
test('relay forwards opaque ciphertext and has no decrypt key', () => { const source = fs.readFileSync(path.join(__dirname, 'src', 'worker.js'), 'utf8'); assert.match(source, /peer\.send\(event\.data\)/); assert.doesNotMatch(source, /decrypt|privateKey|roomKey/) })
